version: '3'
services:
  db:
    image: postgres:15
    container_name: postgres-15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: 
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - mynetwork
    ports:
      - "5432:5432"
  web:
    build: .
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "3000:3000"
  sidekiq:
    depends_on:
      - db
      - redis_app
    build: .
    command: bundle exec sidekiq
    volumes:
      - app-storage:/rails/storage
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis_app:6400/1

  redis_app:
    build:
      context: ./redis
      dockerfile: ./redis/Dockerfile
    ports:
      - "6379:6379"

volumes:
  postgres_data: {}
  app-storage: {}
networks:
  mynetwork:
